/**
 * Curated Brazilian gym terminology for the most commonly used exercises,
 * keyed by the exact English `name` from the free-exercise-db dataset.
 * Anything not listed here falls back to the automatic MyMemory translation.
 */
export const BR_EXERCISE_NAMES: Record<string, string> = {
  // Agachamentos e pernas
  'Barbell Full Squat': 'Agachamento Livre Completo com Barra',
  'Barbell Squat': 'Agachamento Livre com Barra',
  'Barbell Squat To A Bench': 'Agachamento com Barra até o Banco',
  'Barbell Hack Squat': 'Agachamento Hack com Barra',
  'Barbell Side Split Squat': 'Agachamento Sumô com Barra',
  'Barbell Step Ups': 'Subida no Step com Barra',
  'Barbell Walking Lunge': 'Avanço Caminhando com Barra',
  'Barbell Lunge': 'Avanço com Barra',
  'Bodyweight Squat': 'Agachamento Livre (Peso do Corpo)',
  'Bodyweight Walking Lunge': 'Avanço Caminhando (Peso do Corpo)',
  'Box Squat': 'Agachamento na Caixa',
  'Box Squat with Bands': 'Agachamento na Caixa com Elástico',
  'Box Squat with Chains': 'Agachamento na Caixa com Corrente',
  'Chair Squat': 'Agachamento na Cadeira',
  'Dumbbell Squat': 'Agachamento com Halteres',
  'Dumbbell Squat To A Bench': 'Agachamento com Halteres até o Banco',
  'Dumbbell Lunges': 'Avanço com Halteres',
  'Dumbbell Rear Lunge': 'Avanço Reverso com Halteres',
  'Dumbbell Step Ups': 'Subida no Step com Halteres',
  'Front Barbell Squat': 'Agachamento Frontal com Barra',
  'Front Barbell Squat To A Bench': 'Agachamento Frontal até o Banco',
  'Front Squat (Clean Grip)': 'Agachamento Frontal (Pegada de Clean)',
  'Goblet Squat': 'Agachamento Goblet',
  'Hack Squat': 'Agachamento Hack',
  'Jefferson Squats': 'Agachamento Jefferson',
  'Kneeling Squat': 'Agachamento Ajoelhado',
  'Leg Press': 'Leg Press',
  'Narrow Stance Leg Press': 'Leg Press Pés Fechados',
  'Smith Machine Leg Press': 'Leg Press no Smith',
  'Leg Extensions': 'Cadeira Extensora',
  'Single-Leg Leg Extension': 'Cadeira Extensora Unilateral',
  'Lying Leg Curls': 'Mesa Flexora',
  'Seated Leg Curl': 'Cadeira Flexora',
  'Standing Leg Curl': 'Flexora em Pé',
  'Ball Leg Curl': 'Flexora com Bola Suíça',
  'Seated Band Hamstring Curl': 'Flexora Sentado com Elástico',
  'Narrow Stance Hack Squats': 'Agachamento Hack Pés Fechados',
  'Narrow Stance Squats': 'Agachamento Pés Fechados',
  'Wide Stance Barbell Squat': 'Agachamento Sumô com Barra',
  'One Leg Barbell Squat': 'Agachamento Unilateral com Barra',
  'Overhead Squat': 'Agachamento Overhead',
  'Plie Dumbbell Squat': 'Agachamento Plié com Halteres',
  'Single-Leg High Box Squat': 'Agachamento Unilateral na Caixa Alta',
  'Weighted Sissy Squat': 'Agachamento Sissy com Peso',
  'Smith Machine Squat': 'Agachamento no Smith',
  'Smith Machine Pistol Squat': 'Agachamento Pistol no Smith',
  'Smith Single-Leg Split Squat': 'Agachamento Búlgaro no Smith',
  'Split Squats': 'Agachamento Búlgaro',
  'Split Squat with Dumbbells': 'Agachamento Búlgaro com Halteres',
  'Suspended Split Squat': 'Agachamento Búlgaro Suspenso',
  'Weighted Squat': 'Agachamento com Peso',
  'Zercher Squats': 'Agachamento Zercher',
  'Kettlebell Pistol Squat': 'Agachamento Pistol com Kettlebell',
  'Freehand Jump Squat': 'Agachamento com Salto',
  'Weighted Jump Squat': 'Agachamento com Salto e Peso',
  'Kneeling Jump Squat': 'Agachamento com Salto Ajoelhado',
  'Speed Squats': 'Agachamento Rápido',
  'Speed Box Squat': 'Agachamento Rápido na Caixa',
  'Sit Squats': 'Agachamento no Banco',

  // Quadril e glúteos
  'Barbell Hip Thrust': 'Elevação de Quadril com Barra (Hip Thrust)',
  'Barbell Glute Bridge': 'Ponte de Glúteo com Barra',
  'Single Leg Glute Bridge': 'Ponte de Glúteo Unilateral',
  'Smith Machine Hip Raise': 'Elevação de Quadril no Smith',
  'Glute Kickback': 'Coice no Cabo (Glúteo)',
  'One-Legged Cable Kickback': 'Coice Unilateral no Cabo',
  'Glute Ham Raise': 'Flexão Nórdica de Posterior',
  'Floor Glute-Ham Raise': 'Flexão Nórdica no Chão',
  'Natural Glute Ham Raise': 'Flexão Nórdica Natural',
  'Physioball Hip Bridge': 'Ponte de Quadril com Bola Suíça',

  // Levantamento terra
  'Barbell Deadlift': 'Levantamento Terra com Barra',
  'Romanian Deadlift': 'Levantamento Terra Romeno',
  'Romanian Deadlift from Deficit': 'Terra Romeno com Déficit',
  'Stiff-Legged Barbell Deadlift': 'Stiff com Barra',
  'Stiff-Legged Dumbbell Deadlift': 'Stiff com Halteres',
  'Stiff Leg Barbell Good Morning': 'Bom Dia com Pernas Estendidas',
  'Sumo Deadlift': 'Levantamento Terra Sumô',
  'Sumo Deadlift with Bands': 'Terra Sumô com Elástico',
  'Sumo Deadlift with Chains': 'Terra Sumô com Corrente',
  'Trap Bar Deadlift': 'Levantamento Terra com Barra Hexagonal',
  'Rack Pulls': 'Terra Parcial (Rack Pull)',
  'Rack Pull with Bands': 'Terra Parcial com Elástico',
  'Deficit Deadlift': 'Levantamento Terra com Déficit',
  'Snatch Deadlift': 'Terra para Arranco',
  'Clean Deadlift': 'Terra para Clean',
  'Deadlift with Bands': 'Levantamento Terra com Elástico',
  'Deadlift with Chains': 'Levantamento Terra com Corrente',
  'Good Morning': 'Bom Dia (Good Morning)',
  'Good Morning off Pins': 'Bom Dia a Partir do Rack',
  'Seated Good Mornings': 'Bom Dia Sentado',

  // Peito
  'Barbell Bench Press - Medium Grip': 'Supino Reto com Barra',
  'Barbell Incline Bench Press - Medium Grip': 'Supino Inclinado com Barra',
  'Barbell Guillotine Bench Press': 'Supino Guilhotina',
  'Bench Press - Powerlifting': 'Supino Reto (Powerlifting)',
  'Close-Grip Barbell Bench Press': 'Supino Fechado com Barra',
  'Decline Barbell Bench Press': 'Supino Declinado com Barra',
  'Wide-Grip Barbell Bench Press': 'Supino Aberto com Barra',
  'Wide-Grip Decline Barbell Pullover': 'Pullover Declinado com Barra',
  'Wide-Grip Decline Barbell Bench Press': 'Supino Declinado Aberto',
  'Dumbbell Bench Press': 'Supino Reto com Halteres',
  'Decline Dumbbell Bench Press': 'Supino Declinado com Halteres',
  'Dumbbell Bench Press with Neutral Grip': 'Supino com Halteres Pegada Neutra',
  'One Arm Dumbbell Bench Press': 'Supino Unilateral com Halteres',
  'Incline Dumbbell Press': 'Supino Inclinado com Halteres',
  'Hammer Grip Incline DB Bench Press': 'Supino Inclinado Pegada Martelo',
  'Incline Dumbbell Bench With Palms Facing In': 'Supino Inclinado Pegada Neutra',
  'Machine Bench Press': 'Supino na Máquina',
  'Smith Machine Bench Press': 'Supino no Smith',
  'Smith Machine Incline Bench Press': 'Supino Inclinado no Smith',
  'Smith Machine Decline Press': 'Supino Declinado no Smith',
  'Smith Machine Close-Grip Bench Press': 'Supino Fechado no Smith',
  'Cable Chest Press': 'Supino no Cabo',
  'Standing Cable Chest Press': 'Supino no Cabo em Pé',
  'Incline Cable Chest Press': 'Supino Inclinado no Cabo',
  'Leverage Chest Press': 'Supino na Máquina Articulada',
  'Leverage Decline Chest Press': 'Supino Declinado na Máquina Articulada',
  'Leverage Incline Chest Press': 'Supino Inclinado na Máquina Articulada',
  'Cable Crossover': 'Crucifixo no Cabo (Crossover)',
  'Low Cable Crossover': 'Crossover Baixo',
  'Single-Arm Cable Crossover': 'Crossover Unilateral',
  'Incline Cable Flye': 'Crucifixo Inclinado no Cabo',
  'Flat Bench Cable Flyes': 'Crucifixo Reto no Cabo',
  'Dumbbell Flyes': 'Crucifixo com Halteres',
  'Incline Dumbbell Flyes': 'Crucifixo Inclinado com Halteres',
  'Incline Dumbbell Flyes - With A Twist': 'Crucifixo Inclinado com Rotação',
  'Decline Dumbbell Flyes': 'Crucifixo Declinado com Halteres',
  'One-Arm Flat Bench Dumbbell Flye': 'Crucifixo Unilateral com Halter',
  'Bodyweight Flyes': 'Crucifixo (Peso do Corpo)',
  'Reverse Flyes': 'Crucifixo Invertido',
  'Reverse Flyes With External Rotation': 'Crucifixo Invertido com Rotação Externa',
  'Butterfly': 'Peck Deck (Voador)',
  'Push-Up Wide': 'Flexão Aberta',
  'Pushups': 'Flexão de Braço',
  'Pushups (Close and Wide Hand Positions)': 'Flexão (Pegada Fechada e Aberta)',
  'Decline Push-Up': 'Flexão Declinada',
  'Incline Push-Up': 'Flexão Inclinada',
  'Incline Push-Up Close-Grip': 'Flexão Inclinada Fechada',
  'Incline Push-Up Medium': 'Flexão Inclinada Pegada Média',
  'Incline Push-Up Reverse Grip': 'Flexão Inclinada Pegada Invertida',
  'Incline Push-Up Wide': 'Flexão Inclinada Aberta',
  'Close-Grip Push-Up off of a Dumbbell': 'Flexão Fechada Apoiado no Halter',
  'Push-Ups - Close Triceps Position': 'Flexão Fechada (Foco no Tríceps)',
  'Push-Ups With Feet Elevated': 'Flexão com Pés Elevados',
  'Push-Ups With Feet On An Exercise Ball': 'Flexão com Pés na Bola Suíça',
  'Single-Arm Push-Up': 'Flexão Unilateral',
  'Parallel Bar Dip': 'Paralelas (Mergulho)',
  'Dips - Chest Version': 'Paralelas (Foco no Peito)',
  'Dips - Triceps Version': 'Paralelas (Foco no Tríceps)',
  'Bench Dips': 'Mergulho no Banco',
  'Weighted Bench Dip': 'Mergulho no Banco com Peso',
  'Ring Dips': 'Mergulho nos Argolas',

  // Costas
  'Pullups': 'Barra Fixa',
  'Chin-Up': 'Barra Fixa Supinada',
  'One Arm Chin-Up': 'Barra Fixa Unilateral',
  'Mixed Grip Chin': 'Barra Fixa Pegada Mista',
  'Wide-Grip Lat Pulldown': 'Puxada Frontal Aberta',
  'Close-Grip Front Lat Pulldown': 'Puxada Frontal Fechada',
  'V-Bar Pulldown': 'Puxada com Triângulo',
  'V-Bar Pullup': 'Barra Fixa com Triângulo',
  'Wide-Grip Pulldown Behind The Neck': 'Puxada por Trás Pegada Aberta',
  'Wide-Grip Rear Pull-Up': 'Barra Fixa Aberta por Trás',
  'One Arm Lat Pulldown': 'Puxada Unilateral',
  'Underhand Cable Pulldowns': 'Puxada Pegada Supinada',
  'Straight-Arm Pulldown': 'Puxada com Braços Estendidos',
  'Rope Straight-Arm Pulldown': 'Puxada com Corda Braços Estendidos',
  'Full Range-Of-Motion Lat Pulldown': 'Puxada Frontal Amplitude Total',
  'Rocky Pull-Ups/Pulldowns': 'Puxada Progressiva',
  'Seated Cable Rows': 'Remada Baixa (Cabo Sentado)',
  "Seated One-arm Cable Pulley Rows": 'Remada Baixa Unilateral',
  'Bent Over Barbell Row': 'Remada Curvada com Barra',
  'Bent Over Two-Arm Long Bar Row': 'Remada Curvada com Barra (Pegada Aberta)',
  'Bent Over One-Arm Long Bar Row': 'Remada Curvada Unilateral com Barra',
  'One-Arm Long Bar Row': 'Remada Unilateral com Barra',
  'Bent Over Two-Dumbbell Row': 'Remada Curvada com Halteres',
  'Bent Over Two-Dumbbell Row With Palms In': 'Remada Curvada com Halteres Pegada Neutra',
  'One-Arm Dumbbell Row': 'Remada Unilateral com Halter (Serrote)',
  'Dumbbell Incline Row': 'Remada Inclinada com Halteres',
  'Inverted Row': 'Remada Invertida',
  'Inverted Row with Straps': 'Remada Invertida com Alças',
  'Suspended Row': 'Remada Suspensa (TRX)',
  'T-Bar Row with Handle': 'Remada Cavalinho',
  'Lying T-Bar Row': 'Remada Cavalinho Deitado',
  'Smith Machine Bent Over Row': 'Remada Curvada no Smith',
  'Upright Barbell Row': 'Remada Alta com Barra',
  'Upright Cable Row': 'Remada Alta no Cabo',
  "Smith Machine Upright Row": 'Remada Alta no Smith',
  'Smith Machine One-Arm Upright Row': 'Remada Alta Unilateral no Smith',
  'Standing Dumbbell Upright Row': 'Remada Alta com Halteres',
  'Dumbbell One-Arm Upright Row': 'Remada Alta Unilateral com Halter',
  'Kneeling High Pulley Row': 'Remada Alta Ajoelhado',
  'Kneeling Single-Arm High Pulley Row': 'Remada Alta Unilateral Ajoelhado',
  'Elevated Cable Rows': 'Remada Alta no Cabo Elevado',
  'Reverse Grip Bent-Over Rows': 'Remada Curvada Pegada Supinada',
  'Bodyweight Mid Row': 'Remada Invertida (Peso do Corpo)',
  'Straight Bar Bench Mid Rows': 'Remada no Banco com Barra Reta',
  'Low Pulley Row To Neck': 'Remada Baixa ao Pescoço',
  'Lying Cambered Barbell Row': 'Remada Deitado com Barra Curva',
  'Shotgun Row': 'Remada Unilateral (Shotgun)',
  'Leverage High Row': 'Remada Alta na Máquina Articulada',
  'Leverage Iso Row': 'Remada na Máquina Articulada',
  'Face Pull': 'Puxada para o Rosto (Face Pull)',
  'Barbell Shrug': 'Encolhimento com Barra',
  'Barbell Shrug Behind The Back': 'Encolhimento com Barra Atrás das Costas',
  'Dumbbell Shrug': 'Encolhimento com Halteres',
  'Cable Shrugs': 'Encolhimento no Cabo',
  'Smith Machine Behind the Back Shrug': 'Encolhimento por Trás no Smith',
  'Calf-Machine Shoulder Shrug': 'Encolhimento na Máquina de Panturrilha',
  'Middle Back Shrug': 'Encolhimento (Meio das Costas)',
  'Snatch Shrug': 'Encolhimento para Arranco',
  'Clean Shrug': 'Encolhimento para Clean',
  'Hyperextensions (Back Extensions)': 'Extensão Lombar (Banco Romano)',
  'Hyperextensions With No Hyperextension Bench': 'Extensão Lombar sem Banco',
  'Reverse Hyperextension': 'Extensão Lombar Invertida',
  'Bent-Arm Barbell Pullover': 'Pullover com Barra',
  'Bent-Arm Dumbbell Pullover': 'Pullover com Halter',
  'Straight-Arm Dumbbell Pullover': 'Pullover com Halter (Braços Estendidos)',
  'Gironda Sternum Chins': 'Barra Fixa Esterno (Gironda)',
  'Scapular Pull-Up': 'Barra Fixa Escapular',
  'Side To Side Chins': 'Barra Fixa Lateral',
  'Band Assisted Pull-Up': 'Barra Fixa com Elástico de Apoio',
  'Weighted Pull Ups': 'Barra Fixa com Peso',

  // Ombros
  'Barbell Shoulder Press': 'Desenvolvimento com Barra',
  'Seated Barbell Military Press': 'Desenvolvimento Militar Sentado',
  'Standing Military Press': 'Desenvolvimento Militar em Pé',
  'Standing Barbell Press Behind Neck': 'Desenvolvimento por Trás da Nuca',
  'Standing Bradford Press': 'Desenvolvimento Bradford',
  "Bradford/Rocky Presses": 'Desenvolvimento Bradford/Rocky',
  'Dumbbell Shoulder Press': 'Desenvolvimento com Halteres',
  'Seated Dumbbell Press': 'Desenvolvimento Sentado com Halteres',
  'Arnold Dumbbell Press': 'Desenvolvimento Arnold',
  'Standing Dumbbell Press': 'Desenvolvimento em Pé com Halteres',
  'Standing Alternating Dumbbell Press': 'Desenvolvimento Alternado com Halteres',
  'Standing Palms-In Dumbbell Press': 'Desenvolvimento Pegada Neutra',
  'Standing Palm-In One-Arm Dumbbell Press': 'Desenvolvimento Unilateral Pegada Neutra',
  'Dumbbell One-Arm Shoulder Press': 'Desenvolvimento Unilateral com Halter',
  'Machine Shoulder (Military) Press': 'Desenvolvimento na Máquina',
  'Smith Machine Overhead Shoulder Press': 'Desenvolvimento no Smith',
  'Cable Shoulder Press': 'Desenvolvimento no Cabo',
  'Seated Cable Shoulder Press': 'Desenvolvimento no Cabo Sentado',
  'Alternating Cable Shoulder Press': 'Desenvolvimento Alternado no Cabo',
  'Leverage Shoulder Press': 'Desenvolvimento na Máquina Articulada',
  'Side Lateral Raise': 'Elevação Lateral',
  'Side Laterals to Front Raise': 'Elevação Lateral com Frontal',
  'One-Arm Side Laterals': 'Elevação Lateral Unilateral',
  'One-Arm Incline Lateral Raise': 'Elevação Lateral Inclinada Unilateral',
  'Lying One-Arm Lateral Raise': 'Elevação Lateral Deitado Unilateral',
  'Dumbbell Lying One-Arm Rear Lateral Raise': 'Elevação Lateral Posterior Deitado',
  'Dumbbell Lying Rear Lateral Raise': 'Elevação Posterior Deitado com Halteres',
  'Cable Seated Lateral Raise': 'Elevação Lateral no Cabo Sentado',
  'Bent Over Low-Pulley Side Lateral': 'Elevação Lateral Curvado no Cabo',
  'Alternating Deltoid Raise': 'Elevação de Deltoide Alternada',
  'Standing Low-Pulley Deltoid Raise': 'Elevação de Deltoide no Cabo em Pé',
  'Front Dumbbell Raise': 'Elevação Frontal com Halteres',
  'Front Two-Dumbbell Raise': 'Elevação Frontal com Dois Halteres',
  'Single Dumbbell Raise': 'Elevação Frontal com Um Halter',
  'Front Cable Raise': 'Elevação Frontal no Cabo',
  'Front Incline Dumbbell Raise': 'Elevação Frontal Inclinada com Halteres',
  'Front Plate Raise': 'Elevação Frontal com Anilha',
  'Front Raise And Pullover': 'Elevação Frontal com Pullover',
  'Standing Front Barbell Raise Over Head': 'Elevação Frontal com Barra',
  'Barbell Incline Shoulder Raise': 'Elevação Frontal Inclinada com Barra',
  'Dumbbell Incline Shoulder Raise': 'Elevação Frontal Inclinada com Halteres',
  'Smith Incline Shoulder Raise': 'Elevação Frontal Inclinada no Smith',
  'Bent Over Dumbbell Rear Delt Raise With Head On Bench': 'Elevação Posterior no Banco Inclinado',
  'Seated Bent-Over Rear Delt Raise': 'Elevação Posterior Sentado',
  'Cable Rear Delt Fly': 'Crucifixo Invertido no Cabo',
  'Cable Rope Rear-Delt Rows': 'Remada Posterior no Cabo com Corda',
  'Reverse Machine Flyes': 'Crucifixo Invertido na Máquina',
  'Sled Reverse Flye': 'Crucifixo Invertido na Máquina Articulada',
  'Lying Rear Delt Raise': 'Elevação Posterior Deitado',
  'Seated Front Deltoid': 'Deltoide Anterior Sentado',
  'Cuban Press': 'Desenvolvimento Cubano',
  'Dumbbell Raise': 'Elevação com Halter',
  'Dumbbell Scaption': 'Elevação Escapular com Halteres (Scaption)',
  'Upright Row - With Bands': 'Remada Alta com Elástico',
  'Shoulder Raise': 'Elevação de Ombro',
  'Cable Internal Rotation': 'Rotação Interna de Ombro no Cabo',
  'External Rotation': 'Rotação Externa de Ombro',
  'External Rotation with Band': 'Rotação Externa com Elástico',
  'External Rotation with Cable': 'Rotação Externa no Cabo',
  'Internal Rotation with Band': 'Rotação Interna com Elástico',

  // Bíceps
  'Barbell Curl': 'Rosca Direta com Barra',
  'Barbell Curls Lying Against An Incline': 'Rosca Direta Deitado no Banco Inclinado',
  'Close-Grip Standing Barbell Curl': 'Rosca Direta Pegada Fechada',
  'Wide-Grip Standing Barbell Curl': 'Rosca Direta Pegada Aberta',
  'Reverse Barbell Curl': 'Rosca Inversa com Barra',
  'Reverse Plate Curls': 'Rosca Inversa com Anilha',
  'EZ-Bar Curl': 'Rosca Direta com Barra W',
  'Close-Grip EZ Bar Curl': 'Rosca com Barra W Pegada Fechada',
  'Close-Grip EZ-Bar Curl with Band': 'Rosca com Barra W e Elástico',
  'Dumbbell Bicep Curl': 'Rosca com Halteres',
  'Dumbbell Alternate Bicep Curl': 'Rosca Alternada com Halteres',
  'Alternate Hammer Curl': 'Rosca Martelo Alternada',
  'Hammer Curls': 'Rosca Martelo',
  'Cross Body Hammer Curl': 'Rosca Martelo Cruzada',
  'Incline Hammer Curls': 'Rosca Martelo no Banco Inclinado',
  'Concentration Curls': 'Rosca Concentrada',
  'Standing Concentration Curl': 'Rosca Concentrada em Pé',
  'Seated Close-Grip Concentration Barbell Curl': 'Rosca Concentrada Sentado com Barra',
  'Preacher Curl': 'Rosca Scott',
  'Preacher Hammer Dumbbell Curl': 'Rosca Scott Martelo',
  'Machine Preacher Curls': 'Rosca Scott na Máquina',
  'One Arm Dumbbell Preacher Curl': 'Rosca Scott Unilateral',
  'Reverse Barbell Preacher Curls': 'Rosca Scott Inversa',
  'Two-Arm Dumbbell Preacher Curl': 'Rosca Scott com Halteres',
  'Spider Curl': 'Rosca Spider (Aranha)',
  'Standing Biceps Cable Curl': 'Rosca Direta no Cabo',
  'Cable Hammer Curls - Rope Attachment': 'Rosca Martelo no Cabo com Corda',
  'High Cable Curls': 'Rosca no Cabo Alto',
  'Standing One-Arm Cable Curl': 'Rosca Unilateral no Cabo',
  'Overhead Cable Curl': 'Rosca no Cabo Alto (Bilateral)',
  'Seated Dumbbell Curl': 'Rosca Sentado com Halteres',
  'Alternate Incline Dumbbell Curl': 'Rosca Alternada no Banco Inclinado',
  'Incline Dumbbell Curl': 'Rosca no Banco Inclinado',
  'Flexor Incline Dumbbell Curls': 'Rosca Inclinada (Flexores)',
  'Standing One-Arm Dumbbell Curl Over Incline Bench': 'Rosca Unilateral Apoiado no Banco',
  'Seated Dumbbell Inner Biceps Curl': 'Rosca Concentrada Sentado',
  'Standing Inner-Biceps Curl': 'Rosca Concentrada em Pé',
  'Incline Inner Biceps Curl': 'Rosca Concentrada no Banco Inclinado',
  'Zottman Curl': 'Rosca Zottman',
  'Zottman Preacher Curl': 'Rosca Scott Zottman',
  'Drag Curl': 'Rosca Arrastada (Drag Curl)',
  'Machine Bicep Curl': 'Rosca na Máquina',
  'Lying Cable Curl': 'Rosca Deitado no Cabo',
  'Lying Close-Grip Bar Curl On High Pulley': 'Rosca Deitado Pegada Fechada no Cabo',
  'Lying High Bench Barbell Curl': 'Rosca Deitado no Banco Alto',
  'Lying Supine Dumbbell Curl': 'Rosca Deitado com Halteres',
  'Cross-Body Crunch': 'Abdominal Cruzado',
  'Reverse Cable Curl': 'Rosca Inversa no Cabo',
  'Seated Biceps': 'Rosca Bíceps Sentado',
  'Standing Dumbbell Reverse Curl': 'Rosca Inversa com Halteres',

  // Tríceps
  'Triceps Pushdown': 'Tríceps Pulley (Barra Reta)',
  'Triceps Pushdown - Rope Attachment': 'Tríceps Corda',
  'Triceps Pushdown - V-Bar Attachment': 'Tríceps Pulley (Barra V)',
  'Reverse Grip Triceps Pushdown': 'Tríceps Pulley Pegada Supinada',
  'Cable Rope Overhead Triceps Extension': 'Tríceps Testa no Cabo com Corda',
  'Cable Incline Triceps Extension': 'Tríceps no Cabo Inclinado',
  'Cable Lying Triceps Extension': 'Tríceps Deitado no Cabo',
  'Cable One Arm Tricep Extension': 'Tríceps Unilateral no Cabo',
  'Kneeling Cable Triceps Extension': 'Tríceps Ajoelhado no Cabo',
  'Low Cable Triceps Extension': 'Tríceps no Cabo Baixo',
  'Chain Handle Extension': 'Tríceps com Corrente',
  'Standing Overhead Barbell Triceps Extension': 'Tríceps Testa em Pé com Barra',
  'Incline Barbell Triceps Extension': 'Tríceps Testa Inclinado com Barra',
  'Lying Triceps Press': 'Tríceps Testa (Francês)',
  'Lying Close-Grip Barbell Triceps Extension Behind The Head': 'Tríceps Testa por Trás da Cabeça',
  'Lying Close-Grip Barbell Triceps Press To Chin': 'Tríceps Testa até o Queixo',
  'Lying Dumbbell Tricep Extension': 'Tríceps Testa com Halteres',
  'EZ-Bar Skullcrusher': 'Tríceps Testa com Barra W',
  'Decline EZ Bar Triceps Extension': 'Tríceps Testa Declinado com Barra W',
  'Decline Close-Grip Bench To Skull Crusher': 'Supino Fechado Declinado com Tríceps Testa',
  'Seated Triceps Press': 'Tríceps Francês Sentado',
  'Seated Bent-Over One-Arm Dumbbell Triceps Extension': 'Tríceps Francês Curvado Unilateral',
  'Seated Bent-Over Two-Arm Dumbbell Triceps Extension': 'Tríceps Francês Curvado com Halteres',
  'Standing Bent-Over One-Arm Dumbbell Triceps Extension': 'Tríceps Francês Curvado em Pé (Unilateral)',
  'Standing Bent-Over Two-Arm Dumbbell Triceps Extension': 'Tríceps Francês Curvado em Pé',
  'Standing Dumbbell Triceps Extension': 'Tríceps Francês em Pé com Halter',
  'Standing One-Arm Dumbbell Triceps Extension': 'Tríceps Francês Unilateral em Pé',
  'Dumbbell One-Arm Triceps Extension': 'Tríceps Francês Unilateral',
  'Decline Dumbbell Triceps Extension': 'Tríceps Francês Declinado',
  'Dumbbell Tricep Extension -Pronated Grip': 'Tríceps Francês Pegada Pronada',
  'One Arm Pronated Dumbbell Triceps Extension': 'Tríceps Unilateral Pegada Pronada',
  'One Arm Supinated Dumbbell Triceps Extension': 'Tríceps Unilateral Pegada Supinada',
  'Standing Towel Triceps Extension': 'Tríceps com Toalha em Pé',
  'Standing Low-Pulley One-Arm Triceps Extension': 'Tríceps Unilateral no Cabo Baixo',
  'Sled Overhead Triceps Extension': 'Tríceps Testa na Máquina Articulada',
  'Tricep Dumbbell Kickback': 'Tríceps Coice com Halter',
  'Close-Grip Dumbbell Press': 'Supino Fechado com Halteres',
  'JM Press': 'JM Press (Tríceps)',
  'Tate Press': 'Tate Press (Tríceps)',
  'Board Press': 'Board Press (Supino com Apoio)',
  'Machine Triceps Extension': 'Tríceps na Máquina',
  'Body Tricep Press': 'Tríceps no Peso do Corpo',
  'Body-Up': 'Tríceps no Banco (Peso do Corpo)',
  'Triceps Overhead Extension with Rope': 'Tríceps Testa com Corda',
  'Reverse Triceps Bench Press': 'Supino Pegada Invertida (Tríceps)',

  // Antebraço
  'Wrist Roller': 'Rolo de Punho',
  'Wrist Circles': 'Rotação de Punho',
  'Wrist Rotations with Straight Bar': 'Rotação de Punho com Barra Reta',
  'Cable Wrist Curl': 'Rosca de Punho no Cabo',
  'Finger Curls': 'Rosca de Dedos',
  'Palms-Down Dumbbell Wrist Curl Over A Bench': 'Rosca de Punho com Halteres (Pronada)',
  'Palms-Down Wrist Curl Over A Bench': 'Rosca de Punho com Barra (Pronada)',
  'Palms-Up Barbell Wrist Curl Over A Bench': 'Rosca de Punho com Barra (Supinada)',
  'Palms-Up Dumbbell Wrist Curl Over A Bench': 'Rosca de Punho com Halteres (Supinada)',
  'Seated Dumbbell Palms-Down Wrist Curl': 'Rosca de Punho Sentado (Pronada)',
  'Seated Dumbbell Palms-Up Wrist Curl': 'Rosca de Punho Sentado (Supinada)',
  'Seated One-Arm Dumbbell Palms-Down Wrist Curl': 'Rosca de Punho Unilateral (Pronada)',
  'Seated One-Arm Dumbbell Palms-Up Wrist Curl': 'Rosca de Punho Unilateral (Supinada)',
  'Seated Palm-Up Barbell Wrist Curl': 'Rosca de Punho Sentado com Barra (Supinada)',
  'Seated Palms-Down Barbell Wrist Curl': 'Rosca de Punho Sentado com Barra (Pronada)',
  'Seated Two-Arm Palms-Up Low-Pulley Wrist Curl': 'Rosca de Punho no Cabo Sentado',
  'Standing Palms-Up Barbell Behind The Back Wrist Curl': 'Rosca de Punho Atrás das Costas',
  "Farmer's Walk": 'Caminhada do Fazendeiro',

  // Abdômen
  'Crunches': 'Abdominal Crunch',
  'Sit-Up': 'Abdominal Reto (Sit-Up)',
  'Jackknife Sit-Up': 'Abdominal Canivete',
  'Janda Sit-Up': 'Abdominal Janda',
  'Press Sit-Up': 'Abdominal com Peso',
  'Frog Sit-Ups': 'Abdominal Sapo',
  'Weighted Sit-Ups - With Bands': 'Abdominal com Elástico',
  '3/4 Sit-Up': 'Abdominal 3/4',
  'Cable Crunch': 'Abdominal no Cabo',
  'Cable Seated Crunch': 'Abdominal Sentado no Cabo',
  'Kneeling Cable Crunch With Alternating Oblique Twists': 'Abdominal Ajoelhado com Torção no Cabo',
  'Decline Crunch': 'Abdominal Declinado',
  'Decline Oblique Crunch': 'Abdominal Oblíquo Declinado',
  'Reverse Crunch': 'Abdominal Infra (Reverso)',
  'Decline Reverse Crunch': 'Abdominal Infra Declinado',
  'Suspended Reverse Crunch': 'Abdominal Infra Suspenso',
  'Crunch - Hands Overhead': 'Abdominal com Braços Estendidos',
  'Crunch - Legs On Exercise Ball': 'Abdominal com Pernas na Bola Suíça',
  'Exercise Ball Crunch': 'Abdominal na Bola Suíça',
  'Bosu Ball Cable Crunch With Side Bends': 'Abdominal no Bosu com Torção Lateral',
  'Rope Crunch': 'Abdominal com Corda',
  'Standing Rope Crunch': 'Abdominal em Pé com Corda',
  'Weighted Crunches': 'Abdominal com Peso',
  'Ab Crunch Machine': 'Abdominal na Máquina',
  'Ab Roller': 'Roda Abdominal',
  'Barbell Ab Rollout': 'Rollout Abdominal com Barra',
  'Barbell Ab Rollout - On Knees': 'Rollout Abdominal Ajoelhado',
  'Barbell Rollout from Bench': 'Rollout Abdominal no Banco',
  'Oblique Crunches': 'Abdominal Oblíquo',
  'Oblique Crunches - On The Floor': 'Abdominal Oblíquo no Chão',
  'Hanging Leg Raise': 'Elevação de Pernas na Barra',
  'Hanging Pike': 'Elevação de Pernas na Barra (Pike)',
  'Flat Bench Lying Leg Raise': 'Elevação de Pernas no Banco',
  'Flat Bench Leg Pull-In': 'Elevação de Joelhos no Banco',
  'Seated Flat Bench Leg Pull-In': 'Elevação de Joelhos Sentado',
  'Leg Pull-In': 'Elevação de Joelhos',
  'Leg Lift': 'Elevação de Pernas',
  'Front Leg Raises': 'Elevação de Pernas Frontal',
  'Rear Leg Raises': 'Elevação de Pernas Posterior',
  'Side Leg Raises': 'Elevação de Pernas Lateral',
  'Knee/Hip Raise On Parallel Bars': 'Elevação de Joelhos nas Paralelas',
  'Plank': 'Prancha',
  'Side Bridge': 'Prancha Lateral',
  'Push Up to Side Plank': 'Flexão com Prancha Lateral',
  'Russian Twist': 'Torção Russa (Russian Twist)',
  'Cable Russian Twists': 'Torção Russa no Cabo',
  'Seated Barbell Twist': 'Torção com Barra Sentado',
  'Standing Cable Wood Chop': 'Lenhador no Cabo',
  'Standing Cable Lift': 'Elevação no Cabo (Torção)',
  'Pallof Press': 'Pallof Press',
  'Pallof Press With Rotation': 'Pallof Press com Rotação',
  'One-Arm High-Pulley Cable Side Bends': 'Torção Lateral no Cabo Alto',
  'Dumbbell Side Bend': 'Torção Lateral com Halter',
  'Barbell Side Bend': 'Torção Lateral com Barra',
  'Weighted Ball Side Bend': 'Torção Lateral com Bola de Peso',
  'Otis-Up': 'Abdominal Otis-Up',
  'Dead Bug': 'Dead Bug (Inseto Morto)',
  'Stomach Vacuum': 'Vácuo Abdominal',
  'Air Bike': 'Bicicleta Abdominal (Air Bike)',
  'Alternate Heel Touchers': 'Toque no Calcanhar Alternado',
  'Toe Touchers': 'Toque nos Pés',
  'Flutter Kicks': 'Tesoura de Pernas',
  'Mountain Climbers': 'Escalador (Mountain Climber)',

  // Panturrilha
  'Standing Calf Raises': 'Panturrilha em Pé',
  'Rocking Standing Calf Raise': 'Panturrilha em Pé (Balanço)',
  'Seated Calf Raise': 'Panturrilha Sentado',
  'Standing Barbell Calf Raise': 'Panturrilha em Pé com Barra',
  'Standing Dumbbell Calf Raise': 'Panturrilha em Pé com Halteres',
  'Donkey Calf Raises': 'Panturrilha Burrinho',
  'Calf Press': 'Panturrilha no Leg Press',
  'Calf Press On The Leg Press Machine': 'Panturrilha no Leg Press',
  'Calf Raise On A Dumbbell': 'Panturrilha em Cima do Halter',
  'Calf Raises - With Bands': 'Panturrilha com Elástico',
  'Smith Machine Calf Raise': 'Panturrilha no Smith',
  'Smith Machine Reverse Calf Raises': 'Panturrilha Invertida no Smith',
  'Dumbbell Seated One-Leg Calf Raise': 'Panturrilha Sentado Unilateral',

  // Cardio e outros
  'Jogging, Treadmill': 'Corrida Leve na Esteira',
  'Running, Treadmill': 'Corrida na Esteira',
  'Walking, Treadmill': 'Caminhada na Esteira',
  'Elliptical Trainer': 'Elíptico',
  'Recumbent Bike': 'Bicicleta Ergométrica Reclinada',
  'Bicycling, Stationary': 'Bicicleta Ergométrica',
  'Bicycling': 'Ciclismo',
  'Stairmaster': 'Escada Ergométrica (Stairmaster)',
  'Step Mill': 'Escada Ergométrica (Step Mill)',
  'Rowing, Stationary': 'Remo Ergométrico',
  'Rope Jumping': 'Pular Corda',
  'Fast Skipping': 'Pular Corda Rápido',
  'Battling Ropes': 'Corda Naval (Battle Rope)',
  'Box Jump (Multiple Response)': 'Salto na Caixa',
  'Front Box Jump': 'Salto Frontal na Caixa',
  'Lateral Box Jump': 'Salto Lateral na Caixa',
  'Burpee': 'Burpee',

  // Halterofilismo/Kettlebell/Crossfit
  'Clean': 'Clean',
  'Clean and Jerk': 'Clean e Arranco (Clean and Jerk)',
  'Clean and Press': 'Clean e Desenvolvimento',
  'Power Clean': 'Power Clean',
  'Hang Clean': 'Hang Clean',
  'Dumbbell Clean': 'Clean com Halteres',
  'Snatch': 'Arranco (Snatch)',
  'Power Snatch': 'Power Snatch',
  'Hang Snatch': 'Hang Snatch',
  'Push Press': 'Push Press',
  'Push Press - Behind the Neck': 'Push Press por Trás da Nuca',
  'Split Jerk': 'Split Jerk',
  'Power Jerk': 'Power Jerk',
  'Kettlebell Swing': 'Balanço com Kettlebell (Swing)',
  'One-Arm Kettlebell Swings': 'Balanço Unilateral com Kettlebell',
  'Kettlebell Goblet Squat': 'Agachamento Goblet com Kettlebell',
  'Kettlebell Turkish Get-Up (Squat style)': 'Turkish Get-Up com Kettlebell (Agachamento)',
  'Kettlebell Turkish Get-Up (Lunge style)': 'Turkish Get-Up com Kettlebell (Avanço)',
  'Kettlebell Windmill': 'Moinho de Vento com Kettlebell',
  'Kettlebell Arnold Press': 'Desenvolvimento Arnold com Kettlebell',
  'Kettlebell Seated Press': 'Desenvolvimento Sentado com Kettlebell',
  'Kettlebell Sumo High Pull': 'Puxada Alta Sumô com Kettlebell',
  'Kettlebell Thruster': 'Thruster com Kettlebell',
}

export function curatedName(name: string): string | undefined {
  return BR_EXERCISE_NAMES[name]
}
